# This action triggers the build hook
name: Schedule Daily Image generation

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build hook request
        run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}