# This action triggers the build hook
name: Schedule Build & Deploy Hooks
description: Schedules builds of static sites on services like Netlify and Vercel by triggering build hooks.
branding:
  icon: "clock"
  color: "blue"
on:
  schedule:
    - cron: "10 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build hook request
        run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}