# This action triggers the build hook
name: Schedule Daily Image generation

on:
  schedule:
    - cron: "40 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build hook request
        run: curl -X POST -d {} ${{ secrets.BUILD_HOOK }}